language: ruby
rvm:
- 2.2
install: gem install ruby_dep -v 1.3.1 && gem install jekyll -v 2.4.0 && gem install
  s3_website
script: jekyll build
after_success: s3_website push
"-deploy":
- provider: s3
- access_key_id: AKIAID6VL325SNHJY6FQ
- secret_access_key: 
- secure: MCqqAwGMdxUkwc6UTMFInEyIIkTlbxSYxiUB2YFk49EtT8Z9OiGrml9bmEVzHBGhC1rHmJeZUcvOzzAY40RC9s3n9hqR0ncpgUoY864odgetzvy6/ZKC97ljSm53cr9aIqQt0EhiUVS/l6iymBGU8VL0c8lZN1JUJNibBSgklr/ODt0nX1kt4QWkLHG7M9/Tbt6N7rF3ceGUCAk9QyZ6QRV2VNQ1/JIE/RNczobd+HcHX/5v7H+4h4opb4nFF1WNajpFrp33lBAQJ3Mx6mJ4b6b7CRrsx8Z6TjW5fohwsr3Lzw0Hpy7/M0Vkw57E2V73mwAiz0Kes8Z3o53iyutRYzFMEzYotI7DiBz4YyoOpI1r/hc6bqGIXFDikWeZr7Vco6Guc6giAYCsK4TRWSssPw24OPxsxV+DqK4qm/ik/xyZK2X2s4qlC3oNJuEW3oXr5EZmOEOBE9kNf5E6M+oHeqzx3T35OBFrK5BN8Pln8u959Hzi+I7GmfIqPBOmrlH8yPSDnJnGEodqFlfsP8Z1gCAdTKOmWv5TfqMH9Wn0GWzDL6eZDYcuP3MzQ9/VKexG9nYZ95LcOabcZzUGOqPr8iGlbKQR/jCtVL+/UTwRJNrZFxcYckM8cZ9jTuQKzs5wv78M07DwV6YaGUnVCpkqa/6beeWHcmye0ia/yhWcsN4=
- bucket: matador.network
- acl: public_read
deploy:
  provider: s3
  access_key_id: AKIAID6VL325SNHJY6FQ
  secret_access_key:
    secure: ZYyoYqL4JGCqoc3hT4eLvqaUi0409phO9rmsdFkIvpjgzWF59T6AzCYmpc9p4JMc6+FDG/2tvY1MiKd+QHWvAnw0TBG9QPM9Ps+V/zzl9t31Yee+P/HbwQ1qTyC8dhMkkrmTF6Meneqxx8xN7R26Ci1t6KN6jujIk+lbxas3DjEybAniGi4QN0yTE3EEjK6lI3ECANN7zbaotDv+hoxGWkVLFfXSjNWGalnOC8ZVMH1ZhG/XYSZFlZPcv+EGNb+TRcIu2/RnSIMpk6TzHZ7QZofGfQ5BdtrXwkN9yUFs4S3ws+9j75+A8d2L6vnVtVPNSYQaf0qoQkgkevMlQ+8auOS43oLeTWWTi7++edtfWnhgeeQs40hV/kRwum5MsCCsK/Bz75xZIBpuQWu8ha9WOejT1v4q0jij70Zn5KHOZpqlhEG6HfzN0ts9kVb3Dex1LHi3WKhgoJJmRfTExBbzlPGSd/z6vEDOb25nqS9JV1gVfJIpJtx+hk3ET5Tlu2ecEnKwWPWFfClptzJLmzsZIClbXiHsdmFpc8pHJEAPMsZCiljfXke266Pw/wUyFYqj2UEw8OinZoNnH8p4DWnC9IIkxeIdMwnu+oDXwzCq9mG8AF64DRSXatOgtNgUouXC4ZdZH5FkysMMTqWBu2xudcWho5hmDnyZIFdeQ+l6ia0=
  bucket: matador.network
  upload-dir: matador.network
  acl: public_read
  on:
    repo: PolymathNetwork/matador-landing
