install:
  - yarn install

env:
  - CI="true"

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "**/node_modules"

#before_script:
#  - scripts/installs.sh

script:
#  - scripts/run.sh
  - scripts/installs.sh
